SERVER = "https://techvented.com"
LOCALHOST = "http://localhost"

QUILL_URL = 'https://quillbot.com/'
TECH_POINT_URL = 'https://disrupt-africa.com/'

# JOB STATUS
RAN = 'RAN'
RUNNING = 'RUNNING'
PENDING = 'PENDING'
QUEUED = 'QUEUED'
FAILED = 'FAILED'
TIMEOUT = 'TIMEOUT'

KEYWORD_CANNIBALIZATION = 'KEYWORD_CANNIBALIZATION'
PARAPHRASING_MISMATCH_ERROR = 'PARAPHRASING_MISMATCH_ERROR'
NO_PARSER_CONFIGURATION = 'NO_PARSER_CONFIGURATION'
MARKED_FOR_INSPECTION = 'MARKED_FOR_INSPECTION'
INSPECTION_IN_PROGRESS = 'INSPECTION_IN_PROGRESS'
INSPECTION_COMPLETED = 'INSPECTION_COMPLETED'
